# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92916d69cd98b287ef024d59e238447e585385d70b1e26343c3e601cf2dbf018bd8501ce3ec817bbc3be48d566d49dcb843f67a8d5f692d7c61d2731a6b0d522

test:
  secret_key_base: cdd4361739f7c325aaae440880cf615763ffa54e1debb3f0ec51e9df563015f7322f7aabf81dd22ccdf3d6a9df40585da0dd6140bcc42d84daac09c93addf2f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
